# Generated by Django 6.0 on 2025-12-27 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char1', models.PositiveIntegerField(verbose_name='null=False, blank=False')),
                ('char2', models.PositiveIntegerField(blank=True, verbose_name='null=False, blank=True')),
                ('char3', models.PositiveIntegerField(null=True, verbose_name='null=True, blank=False')),
                ('char4', models.PositiveIntegerField(blank=True, null=True, verbose_name='null=True, blank=True')),
            ],
            options={
                'verbose_name': '文字列テスト',
                'verbose_name_plural': '文字列テスト',
                'db_table': 'char_test',
            },
        ),
        migrations.CreateModel(
            name='DateTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.PositiveIntegerField(verbose_name='null=False, blank=False')),
                ('date2', models.PositiveIntegerField(blank=True, verbose_name='null=False, blank=True')),
                ('date3', models.PositiveIntegerField(null=True, verbose_name='null=True, blank=False')),
                ('date4', models.PositiveIntegerField(blank=True, null=True, verbose_name='null=True, blank=True')),
            ],
            options={
                'verbose_name': '日付テスト',
                'verbose_name_plural': '日付テスト',
                'db_table': 'date_test',
            },
        ),
        migrations.CreateModel(
            name='FieldTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int1', models.PositiveIntegerField(db_column='PositiveInteger1', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='PositiveInteger1')),
                ('int2', models.PositiveIntegerField(db_column='PositiveInteger2', db_default=0, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='PositiveInteger2')),
                ('char1', models.CharField(db_column='Char1', max_length=4, verbose_name='Char1')),
                ('char2', models.CharField(blank=True, db_column='Char2', max_length=4, verbose_name='Char2')),
                ('char3', models.CharField(blank=True, db_column='Char3', db_default='', default='', max_length=4, verbose_name='Char3')),
                ('date1', models.DateTimeField(db_column='DateTime1', verbose_name='DateTime1')),
                ('date2', models.DateTimeField(blank=True, db_column='DateTime2', null=True, verbose_name='DateTime2')),
            ],
            options={
                'verbose_name': 'フィールドテスト',
                'verbose_name_plural': 'フィールドテスト',
                'db_table': 'field_test',
            },
        ),
        migrations.CreateModel(
            name='IntTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int1', models.PositiveIntegerField(verbose_name='null=False, blank=False')),
                ('int2', models.PositiveIntegerField(blank=True, verbose_name='null=False, blank=True')),
                ('int3', models.PositiveIntegerField(null=True, verbose_name='null=True, blank=False')),
                ('int4', models.PositiveIntegerField(blank=True, null=True, verbose_name='null=True, blank=True')),
            ],
            options={
                'verbose_name': '整数型テスト',
                'verbose_name_plural': '整数型テスト',
                'db_table': 'int_test',
            },
        ),
        migrations.CreateModel(
            name='NameMst',
            fields=[
                ('cd', models.PositiveIntegerField(db_column='コード', db_default=0, default=0, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='コード')),
                ('nm', models.CharField(blank=True, db_column='名称', max_length=10, verbose_name='名称')),
                ('digit', models.PositiveIntegerField(db_column='表示桁数', db_default=0, default=0, verbose_name='表示桁数')),
                ('sort', models.PositiveIntegerField(db_column='表示順', db_default=0, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='表示順')),
                ('memo', models.TextField(blank=True, db_column='備考', db_default='', default='', verbose_name='備考')),
                ('ins_at', models.DateTimeField(auto_now_add=True)),
                ('upd_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '名称マスタ',
                'verbose_name_plural': '名称マスタ',
                'db_table': 'name_mst',
            },
        ),
    ]
