# Generated by Django 6.0.1 on 2026-02-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaiinfoTbl',
            fields=[
                ('denno', models.CharField(db_column='伝票番号', max_length=14, primary_key=True, serialize=False, verbose_name='伝票番号')),
                ('den_type', models.CharField(db_column='伝票タイプ', max_length=1, verbose_name='伝票タイプ')),
                ('ins_at', models.DateTimeField(auto_now_add=True)),
                ('upd_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '配送情報テーブル',
                'verbose_name_plural': '配送情報テーブル',
                'db_table': 'haiinfo_tbl',
            },
        ),
        migrations.CreateModel(
            name='KiriTble',
            fields=[
                ('denno', models.CharField(db_column='親伝票番号', max_length=14, verbose_name='親伝票番号')),
                ('s_denno', models.CharField(db_column='子伝票番号', max_length=14, primary_key=True, serialize=False, verbose_name='子伝票番号')),
                ('ins_at', models.DateTimeField(auto_now_add=True)),
                ('upd_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '切り分けテーブル',
                'verbose_name_plural': '切り分けテーブル',
                'db_table': 'kiri_tble',
            },
        ),
    ]
