# Generated by Django 6.0.1 on 2026-02-06 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0002_haiinfotbl_kiritble'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KiriTble',
            new_name='KiriTbl',
        ),
    ]
