# Generated by Django 6.0.1 on 2026-02-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0003_rename_kiritble_kiritbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='haiinfotbl',
            name='order_date',
            field=models.DateTimeField(db_column='注文日時', null=True, verbose_name='注文日時'),
        ),
    ]
